In [ ]:
# ==== IMPORTS ====
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import os

# ==== SEED (reprodutibilidade) ====
np.random.seed(42)

# ==== ESTRUTURA DE PASTAS ====
BASE_DIR = "/content/custo-vida-brasil"
RAW_DIR = f"{BASE_DIR}/data/raw"
PROCESSED_DIR = f"{BASE_DIR}/data/processed"
ANALYTICS_DIR = f"{BASE_DIR}/data/analytics"

for d in [RAW_DIR, PROCESSED_DIR, ANALYTICS_DIR]:
    os.makedirs(d, exist_ok=True)

print("Estrutura criada com sucesso.")

Estrutura criada com sucesso.

In [ ]:
# ==== DIMENSÃO: LOJAS ====
lojas = pd.DataFrame({
    "loja_id": [f"L{i:02d}" for i in range(1, 11)],
    "nome_loja": [f"Sabor & Cia - Unidade {i}" for i in range(1, 11)],
    "regiao": [
        "Capital", "Capital", "Capital",
        "Grande SP", "Grande SP",
        "Interior", "Interior", "Interior",
        "Interior", "Litoral"
    ],
    "cidade": [
        "São Paulo", "São Paulo", "São Paulo",
        "Guarulhos", "Osasco",
        "Campinas", "Sorocaba", "Ribeirão Preto",
        "São José do Rio Preto", "Santos"
    ]
})

# ==== DIMENSÃO: CATEGORIAS ====
categorias = pd.DataFrame({
    "categoria_id": [f"C{i:02d}" for i in range(1, 9)],
    "categoria": [
        "Mercearia", "Hortifruti", "Açougue", "Laticínios",
        "Limpeza", "Higiene", "Bebidas", "Padaria"
    ]
})

lojas.to_parquet(f"{RAW_DIR}/dim_lojas.parquet", index=False)
categorias.to_parquet(f"{RAW_DIR}/dim_categorias.parquet", index=False)

print(lojas)
print(categorias)

  loja_id                 nome_loja     regiao                 cidade
0     L01   Sabor & Cia - Unidade 1    Capital              São Paulo
1     L02   Sabor & Cia - Unidade 2    Capital              São Paulo
2     L03   Sabor & Cia - Unidade 3    Capital              São Paulo
3     L04   Sabor & Cia - Unidade 4  Grande SP              Guarulhos
4     L05   Sabor & Cia - Unidade 5  Grande SP                 Osasco
5     L06   Sabor & Cia - Unidade 6   Interior               Campinas
6     L07   Sabor & Cia - Unidade 7   Interior               Sorocaba
7     L08   Sabor & Cia - Unidade 8   Interior         Ribeirão Preto
8     L09   Sabor & Cia - Unidade 9   Interior  São José do Rio Preto
9     L10  Sabor & Cia - Unidade 10    Litoral                 Santos
  categoria_id   categoria
0          C01   Mercearia
1          C02  Hortifruti
2          C03     Açougue
3          C04  Laticínios
4          C05     Limpeza
5          C06     Higiene
6          C07     Bebidas
7          C08     Padaria

In [ ]:
# ==== DIMENSÃO: PRODUTOS ====
# Cada categoria terá alguns produtos representativos, com preço e custo base

produtos_por_categoria = {
    "C01": [("Arroz 5kg", 24.90, 16.50), ("Feijão 1kg", 8.90, 5.80), ("Açúcar 1kg", 4.50, 2.90), ("Óleo de Soja 900ml", 7.90, 5.20)],
    "C02": [("Banana Prata kg", 5.90, 3.20), ("Tomate kg", 7.50, 4.10), ("Alface unid", 2.50, 1.20), ("Batata kg", 4.90, 2.80)],
    "C03": [("Picanha kg", 59.90, 42.00), ("Frango kg", 12.90, 8.50), ("Linguiça kg", 18.90, 12.30), ("Carne Moída kg", 28.90, 19.50)],
    "C04": [("Leite 1L", 5.20, 3.60), ("Queijo Mussarela kg", 32.90, 22.00), ("Iogurte 170g", 2.80, 1.70), ("Manteiga 200g", 9.90, 6.50)],
    "C05": [("Detergente 500ml", 2.90, 1.60), ("Sabão em Pó 1kg", 12.90, 8.20), ("Desinfetante 1L", 6.90, 4.10), ("Água Sanitária 1L", 4.50, 2.60)],
    "C06": [("Sabonete unid", 2.50, 1.30), ("Shampoo 350ml", 14.90, 9.20), ("Papel Higiênico 12un", 19.90, 13.50), ("Creme Dental 90g", 4.90, 2.90)],
    "C07": [("Refrigerante 2L", 8.90, 5.60), ("Cerveja Lata", 3.90, 2.40), ("Água Mineral 1,5L", 3.50, 1.90), ("Suco 1L", 6.90, 4.30)],
    "C08": [("Pão Francês kg", 12.90, 6.50), ("Bolo Fatia", 5.90, 2.80), ("Rosquinha 300g", 7.90, 4.20), ("Torta Salgada", 9.90, 5.50)],
}

produtos_rows = []
pid = 1
for cat_id, itens in produtos_por_categoria.items():
    for nome, preco, custo in itens:
        produtos_rows.append({
            "produto_id": f"P{pid:03d}",
            "categoria_id": cat_id,
            "nome_produto": nome,
            "preco_base": preco,
            "custo_base": custo
        })
        pid += 1

produtos = pd.DataFrame(produtos_rows)
produtos.to_parquet(f"{RAW_DIR}/dim_produtos.parquet", index=False)

print(produtos.shape)
produtos.head(10)

(32, 5)

  produto_id categoria_id        nome_produto  preco_base  custo_base
0       P001          C01           Arroz 5kg        24.9        16.5
1       P002          C01          Feijão 1kg         8.9         5.8
2       P003          C01          Açúcar 1kg         4.5         2.9
3       P004          C01  Óleo de Soja 900ml         7.9         5.2
4       P005          C02     Banana Prata kg         5.9         3.2
5       P006          C02           Tomate kg         7.5         4.1
6       P007          C02         Alface unid         2.5         1.2
7       P008          C02           Batata kg         4.9         2.8
8       P009          C03          Picanha kg        59.9        42.0
9       P010          C03           Frango kg        12.9         8.5

In [ ]:
# ==== CONFIGURAÇÃO TEMPORAL ====
data_inicio = datetime(2024, 1, 1)
data_fim = datetime(2024, 12, 31)
datas = pd.date_range(data_inicio, data_fim, freq="D")

canais = ["Loja Física", "Delivery/App"]

vendas_rows = []

for _, loja in lojas.iterrows():
    # fator de sazonalidade/volume específico por loja
    fator_loja = np.random.uniform(0.7, 1.3)

    for _, prod in produtos.iterrows():
        # probabilidade base de venda do produto naquele loja, por dia
        prob_venda_dia = np.random.uniform(0.4, 0.9)

        for data in datas:
            if np.random.rand() > prob_venda_dia:
                continue  # não vendeu esse produto nessa loja nesse dia

            # sazonalidade mensal leve
            mes = data.month
            fator_sazonal = 1 + 0.15 * np.sin(2 * np.pi * mes / 12)

            qtd = max(1, int(np.random.poisson(6) * fator_loja * fator_sazonal))

            # preço praticado (com variação de precificação ao longo do ano)
            variacao_preco = np.random.uniform(0.95, 1.25)
            preco_praticado = round(prod["preco_base"] * variacao_preco, 2)

            # desconto aplicado (%)
            desconto_pct = round(np.random.choice(
                [0, 0, 0, 0.05, 0.10, 0.15, 0.20, 0.30],
                p=[0.5, 0.1, 0.1, 0.1, 0.08, 0.06, 0.04, 0.02]
            ), 2)

            preco_final = round(preco_praticado * (1 - desconto_pct), 2)
            canal = np.random.choice(canais, p=[0.8, 0.2])

            vendas_rows.append({
                "data": data,
                "loja_id": loja["loja_id"],
                "produto_id": prod["produto_id"],
                "quantidade": qtd,
                "preco_praticado": preco_praticado,
                "desconto_pct": desconto_pct,
                "preco_final": preco_final,
                "canal": canal
            })

fato_vendas = pd.DataFrame(vendas_rows)
fato_vendas.to_parquet(f"{RAW_DIR}/fato_vendas.parquet", index=False)

print(fato_vendas.shape)
fato_vendas.head(10)

(76688, 8)

,data,loja_id,produto_id,quantidade,preco_praticado,desconto_pct,preco_final,canal
0,2024-01-01,L01,P001,2,30.13,0.00,30.13,Loja Física
1,2024-01-02,L01,P001,4,27.57,0.00,27.57,Loja Física
2,2024-01-03,L01,P001,4,27.50,0.00,27.50,Loja Física
3,2024-01-04,L01,P001,5,28.77,0.00,28.77,Loja Física
4,2024-01-05,L01,P001,3,27.54,0.00,27.54,Loja Física
5,2024-01-07,L01,P001,5,26.09,0.00,26.09,Loja Física
6,2024-01-08,L01,P001,4,31.03,0.05,29.48,Loja Física
7,2024-01-09,L01,P001,5,30.10,0.00,30.10,Loja Física
8,2024-01-10,L01,P001,5,28.98,0.05,27.53,Loja Física
9,2024-01-11,L01,P001,3,23.89,0.00,23.89,Loja Física

In [ ]:
# ==== FATO: ESTOQUE MENSAL + RUPTURA ====
meses = pd.date_range(data_inicio, data_fim, freq="MS")  # início de cada mês

estoque_rows = []

for _, loja in lojas.iterrows():
    for _, prod in produtos.iterrows():
        # nível de estoque médio "alvo" pra esse produto nessa loja
        estoque_alvo = np.random.randint(30, 150)

        for mes in meses:
            estoque_inicial = max(0, int(np.random.normal(estoque_alvo, estoque_alvo * 0.25)))

            # dias em ruptura no mês (0 a X, com maior chance de ser baixo)
            dias_ruptura = int(np.random.choice(
                [0, 1, 2, 3, 4, 5, 8, 12],
                p=[0.45, 0.15, 0.12, 0.10, 0.08, 0.05, 0.03, 0.02]
            ))

            estoque_rows.append({
                "mes_referencia": mes,
                "loja_id": loja["loja_id"],
                "produto_id": prod["produto_id"],
                "estoque_inicial": estoque_inicial,
                "estoque_alvo": estoque_alvo,
                "dias_ruptura_mes": dias_ruptura
            })

fato_estoque = pd.DataFrame(estoque_rows)
fato_estoque.to_parquet(f"{RAW_DIR}/fato_estoque.parquet", index=False)

print(fato_estoque.shape)
fato_estoque.head(10)

(3840, 6)

,mes_referencia,loja_id,produto_id,estoque_inicial,estoque_alvo,dias_ruptura_mes
0,2024-01-01,L01,P001,95,70,1
1,2024-02-01,L01,P001,50,70,0
2,2024-03-01,L01,P001,56,70,1
3,2024-04-01,L01,P001,94,70,0
4,2024-05-01,L01,P001,49,70,0
5,2024-06-01,L01,P001,69,70,0
6,2024-07-01,L01,P001,48,70,0
7,2024-08-01,L01,P001,77,70,3
8,2024-09-01,L01,P001,63,70,5
9,2024-10-01,L01,P001,39,70,0

In [ ]:
# ==== FATO: INVESTIMENTO EM MARKETING ====
canais_marketing = ["Redes Sociais", "Panfletagem", "Rádio Local", "Encarte Promocional"]

marketing_rows = []

for _, loja in lojas.iterrows():
    # nível de investimento "padrão" da loja (algumas investem mais que outras)
    fator_investimento_loja = np.random.uniform(0.6, 1.6)

    for mes in meses:
        for canal_mkt in canais_marketing:
            # nem todo canal é usado em todo mês/loja
            if np.random.rand() > 0.65:
                continue

            valor_base = np.random.uniform(500, 4000)
            valor_investido = round(valor_base * fator_investimento_loja, 2)

            marketing_rows.append({
                "mes_referencia": mes,
                "loja_id": loja["loja_id"],
                "canal_marketing": canal_mkt,
                "valor_investido": valor_investido
            })

fato_marketing = pd.DataFrame(marketing_rows)
fato_marketing.to_parquet(f"{RAW_DIR}/fato_marketing.parquet", index=False)

print(fato_marketing.shape)
fato_marketing.head(10)

(316, 4)

  mes_referencia loja_id      canal_marketing  valor_investido
0     2024-01-01     L01          Panfletagem          1913.25
1     2024-01-01     L01          Rádio Local          3495.78
2     2024-01-01     L01  Encarte Promocional          4436.38
3     2024-02-01     L01          Panfletagem          2586.53
4     2024-02-01     L01          Rádio Local          4710.94
5     2024-02-01     L01  Encarte Promocional          1748.35
6     2024-03-01     L01        Redes Sociais          1699.69
7     2024-03-01     L01  Encarte Promocional          1574.06
8     2024-04-01     L01        Redes Sociais          1282.98
9     2024-04-01     L01          Rádio Local          3905.24

In [ ]:
# ==== VALIDAÇÃO DE QUALIDADE — CAMADA RAW ====

tabelas = {
    "dim_lojas": lojas,
    "dim_categorias": categorias,
    "dim_produtos": produtos,
    "fato_vendas": fato_vendas,
    "fato_estoque": fato_estoque,
    "fato_marketing": fato_marketing,
}

print("=" * 60)
for nome, df in tabelas.items():
    print(f"\n📋 Tabela: {nome}")
    print(f"Shape: {df.shape}")
    print(f"Nulos por coluna:\n{df.isnull().sum()[df.isnull().sum() > 0]}")
    duplicadas = df.duplicated().sum()
    print(f"Linhas duplicadas: {duplicadas}")
    print(f"Tipos de dados:\n{df.dtypes}")
    print("-" * 60)

============================================================

📋 Tabela: dim_lojas
Shape: (10, 4)
Nulos por coluna:
Series([], dtype: int64)
Linhas duplicadas: 0
Tipos de dados:
loja_id      object
nome_loja    object
regiao       object
cidade       object
dtype: object
------------------------------------------------------------

📋 Tabela: dim_categorias
Shape: (8, 2)
Nulos por coluna:
Series([], dtype: int64)
Linhas duplicadas: 0
Tipos de dados:
categoria_id    object
categoria       object
dtype: object
------------------------------------------------------------

📋 Tabela: dim_produtos
Shape: (32, 5)
Nulos por coluna:
Series([], dtype: int64)
Linhas duplicadas: 0
Tipos de dados:
produto_id       object
categoria_id     object
nome_produto     object
preco_base      float64
custo_base      float64
dtype: object
------------------------------------------------------------

📋 Tabela: fato_vendas
Shape: (76688, 8)
Nulos por coluna:
Series([], dtype: int64)
Linhas duplicadas: 0
Tipos de dados:
data               datetime64[ns]
loja_id                    object
produto_id                 object
quantidade                  int64
preco_praticado           float64
desconto_pct              float64
preco_final               float64
canal                      object
dtype: object
------------------------------------------------------------

📋 Tabela: fato_estoque
Shape: (3840, 6)
Nulos por coluna:
Series([], dtype: int64)
Linhas duplicadas: 0
Tipos de dados:
mes_referencia      datetime64[ns]
loja_id                     object
produto_id                  object
estoque_inicial              int64
estoque_alvo                 int64
dias_ruptura_mes             int64
dtype: object
------------------------------------------------------------

📋 Tabela: fato_marketing
Shape: (316, 4)
Nulos por coluna:
Series([], dtype: int64)
Linhas duplicadas: 0
Tipos de dados:
mes_referencia     datetime64[ns]
loja_id                    object
canal_marketing            object
valor_investido           float64
dtype: object
------------------------------------------------------------

In [ ]:
# ==== PROCESSED: ENRIQUECER FATO_VENDAS ====

fato_vendas_proc = fato_vendas.copy()
fato_vendas_proc["data"] = pd.to_datetime(fato_vendas_proc["data"])
fato_vendas_proc["mes_referencia"] = fato_vendas_proc["data"].values.astype("datetime64[M]")

# joins com dimensões
fato_vendas_proc = fato_vendas_proc.merge(produtos[["produto_id", "categoria_id", "nome_produto", "custo_base"]], on="produto_id", how="left")
fato_vendas_proc = fato_vendas_proc.merge(categorias, on="categoria_id", how="left")
fato_vendas_proc = fato_vendas_proc.merge(lojas[["loja_id", "nome_loja", "regiao", "cidade"]], on="loja_id", how="left")

# campos derivados estruturais
fato_vendas_proc["valor_total_venda"] = (fato_vendas_proc["quantidade"] * fato_vendas_proc["preco_final"]).round(2)
fato_vendas_proc["custo_total"] = (fato_vendas_proc["quantidade"] * fato_vendas_proc["custo_base"]).round(2)

# tipos padronizados
for col in ["loja_id", "produto_id", "categoria_id", "canal"]:
    fato_vendas_proc[col] = fato_vendas_proc[col].astype("string")

fato_vendas_proc.to_parquet(f"{PROCESSED_DIR}/fato_vendas_processed.parquet", index=False)

print(fato_vendas_proc.shape)
fato_vendas_proc.head(5)

(76688, 18)

,data,loja_id,produto_id,quantidade,preco_praticado,desconto_pct,preco_final,canal,mes_referencia,categoria_id,nome_produto,custo_base,categoria,nome_loja,regiao,cidade,valor_total_venda,custo_total
0,2024-01-01,L01,P001,2,30.13,0.0,30.13,Loja Física,2024-01-01,C01,Arroz 5kg,16.5,Mercearia,Sabor & Cia - Unidade 1,Capital,São Paulo,60.26,33.0
1,2024-01-02,L01,P001,4,27.57,0.0,27.57,Loja Física,2024-01-01,C01,Arroz 5kg,16.5,Mercearia,Sabor & Cia - Unidade 1,Capital,São Paulo,110.28,66.0
2,2024-01-03,L01,P001,4,27.50,0.0,27.50,Loja Física,2024-01-01,C01,Arroz 5kg,16.5,Mercearia,Sabor & Cia - Unidade 1,Capital,São Paulo,110.00,66.0
3,2024-01-04,L01,P001,5,28.77,0.0,28.77,Loja Física,2024-01-01,C01,Arroz 5kg,16.5,Mercearia,Sabor & Cia - Unidade 1,Capital,São Paulo,143.85,82.5
4,2024-01-05,L01,P001,3,27.54,0.0,27.54,Loja Física,2024-01-01,C01,Arroz 5kg,16.5,Mercearia,Sabor & Cia - Unidade 1,Capital,São Paulo,82.62,49.5

In [ ]:
# Validação: nulos nas colunas trazidas pelos merges
colunas_dimensao = [c for c in fato_vendas_proc.columns if c not in fato_vendas.columns]
print(fato_vendas_proc[colunas_dimensao].isnull().sum())

mes_referencia       0
categoria_id         0
nome_produto         0
custo_base           0
categoria            0
nome_loja            0
regiao               0
cidade               0
valor_total_venda    0
custo_total          0
dtype: int64

In [ ]:
print(fato_estoque.dtypes)
print(fato_estoque.head(3))

mes_referencia      datetime64[ns]
loja_id                     object
produto_id                  object
estoque_inicial              int64
estoque_alvo                 int64
dias_ruptura_mes             int64
dtype: object
  mes_referencia loja_id produto_id  estoque_inicial  estoque_alvo  \
0     2024-01-01     L01       P001               95            70
1     2024-02-01     L01       P001               50            70
2     2024-03-01     L01       P001               56            70

   dias_ruptura_mes
0                 1
1                 0
2                 1

In [ ]:
import pandas as pd

RAW_DIR = "/content/custo-vida-brasil/data/raw"
PROCESSED_DIR = "/content/custo-vida-brasil/data/processed"

dim_lojas = pd.read_parquet(f"{RAW_DIR}/dim_lojas.parquet")
dim_categorias = pd.read_parquet(f"{RAW_DIR}/dim_categorias.parquet")
dim_produtos = pd.read_parquet(f"{RAW_DIR}/dim_produtos.parquet")
fato_vendas = pd.read_parquet(f"{RAW_DIR}/fato_vendas.parquet")
fato_estoque = pd.read_parquet(f"{RAW_DIR}/fato_estoque.parquet")
fato_marketing = pd.read_parquet(f"{RAW_DIR}/fato_marketing.parquet")

print("Raw recarregado:", dim_lojas.shape, dim_categorias.shape, dim_produtos.shape,
      fato_vendas.shape, fato_estoque.shape, fato_marketing.shape)

Raw recarregado: (10, 4) (8, 2) (32, 5) (76688, 8) (3840, 6) (316, 4)

In [ ]:
%who_ls DataFrame

['categorias',
 'df',
 'dim_categorias',
 'dim_lojas',
 'dim_produtos',
 'fato_estoque',
 'fato_marketing',
 'fato_vendas',
 'fato_vendas_proc',
 'lojas',
 'produtos']

In [ ]:
# PROCESSED: PADRONIZAR FATO_ESTOQUE

fato_estoque_proc = fato_estoque.copy()

# Enriquecer com dimensões
fato_estoque_proc = fato_estoque_proc.merge(dim_lojas, on="loja_id", how="left")
fato_estoque_proc = fato_estoque_proc.merge(dim_produtos, on="produto_id", how="left")

# Tipos padronizados
for col in ["loja_id", "produto_id", "categoria_id"]:
    if col in fato_estoque_proc.columns:
        fato_estoque_proc[col] = fato_estoque_proc[col].astype("category")

# Salvar
fato_estoque_proc.to_parquet(f"{PROCESSED_DIR}/fato_estoque_proc.parquet", index=False)

print(fato_estoque_proc.shape)
print(fato_estoque_proc.dtypes)

(3840, 13)
mes_referencia      datetime64[ns]
loja_id                   category
produto_id                category
estoque_inicial              int64
estoque_alvo                 int64
dias_ruptura_mes             int64
nome_loja                   object
regiao                      object
cidade                      object
categoria_id              category
nome_produto                object
preco_base                 float64
custo_base                 float64
dtype: object

In [ ]:
colunas_dimensao = [c for c in fato_estoque_proc.columns if c not in fato_estoque.columns]
print(fato_estoque_proc[colunas_dimensao].isnull().sum())
print(fato_estoque_proc.shape[0] == fato_estoque.shape[0])
print(fato_estoque_proc.shape)

nome_loja       0
regiao          0
cidade          0
categoria_id    0
nome_produto    0
preco_base      0
custo_base      0
dtype: int64
True
(3840, 13)

In [ ]:
print(fato_marketing.dtypes)
print(fato_marketing.head(3))

mes_referencia     datetime64[ns]
loja_id                    object
canal_marketing            object
valor_investido           float64
dtype: object
  mes_referencia loja_id      canal_marketing  valor_investido
0     2024-01-01     L01          Panfletagem          1913.25
1     2024-01-01     L01          Rádio Local          3495.78
2     2024-01-01     L01  Encarte Promocional          4436.38

In [ ]:
# PROCESSED: PADRONIZAR FATO_MARKETING

fato_marketing_proc = fato_marketing.copy()

# Enriquecer com dimensão de lojas
fato_marketing_proc = fato_marketing_proc.merge(dim_lojas, on="loja_id", how="left")

# Tipos padronizados
fato_marketing_proc["loja_id"] = fato_marketing_proc["loja_id"].astype("category")
fato_marketing_proc["canal_marketing"] = fato_marketing_proc["canal_marketing"].astype("category")

# Salvar
fato_marketing_proc.to_parquet(f"{PROCESSED_DIR}/fato_marketing_proc.parquet", index=False)

print(fato_marketing_proc.shape)
print(fato_marketing_proc.dtypes)

(316, 7)
mes_referencia     datetime64[ns]
loja_id                  category
canal_marketing          category
valor_investido           float64
nome_loja                  object
regiao                     object
cidade                     object
dtype: object

In [ ]:
colunas_dimensao = [c for c in fato_marketing_proc.columns if c not in fato_marketing.columns]
print(fato_marketing_proc[colunas_dimensao].isnull().sum())
print(fato_marketing_proc.shape[0] == fato_marketing.shape[0])
print(fato_marketing_proc.shape)

nome_loja    0
regiao       0
cidade       0
dtype: int64
True
(316, 7)

In [ ]:
# PROCESSED: PADRONIZAR DIMENSÕES

dim_lojas_proc = dim_lojas.copy()
dim_categorias_proc = dim_categorias.copy()
dim_produtos_proc = dim_produtos.copy()

# Padroniza tipos categóricos e remove espaços extras em colunas de texto
for df in [dim_lojas_proc, dim_categorias_proc, dim_produtos_proc]:
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].str.strip()

dim_lojas_proc["loja_id"] = dim_lojas_proc["loja_id"].astype("category")
dim_categorias_proc["categoria_id"] = dim_categorias_proc["categoria_id"].astype("category")
dim_produtos_proc["produto_id"] = dim_produtos_proc["produto_id"].astype("category")

# Salvar
dim_lojas_proc.to_parquet(f"{PROCESSED_DIR}/dim_lojas_proc.parquet", index=False)
dim_categorias_proc.to_parquet(f"{PROCESSED_DIR}/dim_categorias_proc.parquet", index=False)
dim_produtos_proc.to_parquet(f"{PROCESSED_DIR}/dim_produtos_proc.parquet", index=False)

print(dim_lojas_proc.shape, dim_categorias_proc.shape, dim_produtos_proc.shape)

(10, 4) (8, 2) (32, 5)

In [ ]:
# Buscar o token guardado no Colab Secrets
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')

# Configurar identidade do Git (ajuste seu e-mail)
!git config --global user.name "klaytonsi"
!git config --global user.email "klaytonsi735@gmail.com"

# Clonar o repositório vazio criado no GitHub
!git clone https://{GITHUB_TOKEN}@github.com/klaytonsi/custo-vida-brasil-margem-varejo.git /content/repo

Cloning into '/content/repo'...
remote: Repository not found.
fatal: repository 'https://github.com/klaytonsi/custo-vida-brasil-margem-varejo.git/' not found

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

!find /content/drive/MyDrive -iname "*custo*vida*ipynb*"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Colab Notebooks/Cópia de custo-vida-brasil-margem-varejo.ipynb
/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo.ipynb

In [ ]:
import os

f1 = "/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo.ipynb"
f2 = "/content/drive/MyDrive/Colab Notebooks/Cópia de custo-vida-brasil-margem-varejo.ipynb"

for f in [f1, f2]:
    stat = os.stat(f)
    print(f, "-> tamanho:", stat.st_size, "bytes | modificado em:", stat.st_mtime)

/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo.ipynb -> tamanho: 81279 bytes | modificado em: 1788694962.0
/content/drive/MyDrive/Colab Notebooks/Cópia de custo-vida-brasil-margem-varejo.ipynb -> tamanho: 88819 bytes | modificado em: 1788695405.0

In [ ]:
import os
print(os.path.exists("/content/repo"))
print(os.listdir("/content"))

False
['.config', 'custo-vida-brasil', 'drive', 'sample_data']

In [ ]:
import os

f1 = "/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo.ipynb"
f2 = "/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo (1).ipynb"

for f in [f1, f2]:
    stat = os.stat(f)
    print(f, "-> tamanho:", stat.st_size, "bytes | modificado em:", stat.st_mtime)

/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo.ipynb -> tamanho: 81279 bytes | modificado em: 1788694962.0
/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo (1).ipynb -> tamanho: 90060 bytes | modificado em: 1788695594.0

In [44]:
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')

!git config --global user.name "klaytonsi"
!git config --global user.email "klaytonsi735@gmail.com"

!git clone https://{GITHUB_TOKEN}@github.com/klaytonsi/custo-vida-brasil-margem-varejo-.git /content/repo

Cloning into '/content/repo'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (5/5), done.

In [45]:
import os

f1 = "/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo.ipynb"
f2 = "/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo (1).ipynb"

for f in [f1, f2]:
    if os.path.exists(f):
        stat = os.stat(f)
        print(f, "-> tamanho:", stat.st_size, "bytes | modificado em:", stat.st_mtime)
    else:
        print(f, "-> não existe")

/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo.ipynb -> tamanho: 81279 bytes | modificado em: 1788694962.0
/content/drive/MyDrive/Colab Notebooks/custo-vida-brasil-margem-varejo (1).ipynb -> tamanho: 85911 bytes | modificado em: 1788696073.0